### ISSUE TITLE
readme.md has too many exceptions

### ISSUE THREAD

**Issue by MeDiamondStar** [Permafrozen/BusinessApplication69#1]
Very detailed readme, but too many exceptions.
Have you considered to
```
guade oide
```
?

Best regards,
Uraniumschutzbunkernotschutzkontaktschalter

**Comment by Permafrozen** [comment]
ummm sori for bed inglish but me no undastand so go fix o somfing yeye

bet regardz,

yours truly

xxxMatteoProgaming5000xx
